#! /bin/bash

# Get keyrings
mkdir -p /etc/apt/keyrings/
wget https://github.com/PikaOS-Linux/pika-base-debian-container/raw/main/pika-keyring.gpg.key -O /etc/apt/keyrings/pika-keyring.gpg.key
wget https://github.com/PikaOS-Linux/pika-base-debian-container/raw/main/deb-multimedia-keyring.gpg -O /etc/apt/keyrings/deb-multimedia-keyring.gpg

rm -fv /etc/apt/sources.list
touch /etc/apt/sources.list

tee /etc/apt/sources.list <<'EOF'
deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian sid main contrib non-free non-free-firmware
deb [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian experimental main contrib non-free non-free-firmware
deb-src [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian sid main contrib non-free non-free-firmware
deb-src [signed-by=/usr/share/keyrings/debian-archive-keyring.gpg] http://deb.debian.org/debian experimental main contrib non-free non-free-firmware
deb [signed-by=/etc/apt/keyrings/deb-multimedia-keyring.gpg] https://www.deb-multimedia.org sid main non-free
deb-src [signed-by=/etc/apt/keyrings/deb-multimedia-keyring.gpg] https://www.deb-multimedia.org sid main non-free
deb [signed-by=/etc/apt/keyrings/pika-keyring.gpg.key] https://ppa.pika-os.com/ pikauwu main
EOF

rm -rf /etc/apt/preferences
touch /etc/apt/preferences

tee /etc/apt/preferences <<'EOF'
# Blacklist Packages from being pulled from debian experimental
Package: *libwebrtc-audio-processing* *selinux*
Pin: release a=experimental
Pin-Priority: -1

Package: *
Pin: release o=Unofficial Multimedia Packages
Pin-Priority: 550

# Give pika lowest priority because we don't want it sources overwriting
Package: *
Pin: release a=pikauwu,c=canary
Pin-Priority: 390

Package: libhsa-runtime64*
Pin: release o=Debian
Pin-Priority: 100

Package: hipcc*
Pin: release o=Debian
Pin-Priority: 100

Package: rocm*
Pin: release o=Debian
Pin-Priority: 100

Package: *
Pin: release c=rocm
Pin-Priority: 400

Package: amdgpu-core amdgpu-pro-core amdgpu-dkms amdgpu-pro-lib32
Pin: release a=*
Pin-Priority: -10


EOF

wget https://github.com/PikaOS-Linux/pika-base-debian-container/raw/main/0-debian-exp-overrides -O /0-debian-exp-overrides

cat /0-debian-exp-overrides >> /etc/apt/preferences

apt-get update -y
apt-get install apt-utils -y